import { type NextPage } from "next";
import Head from "next/head";
import { Button } from 'shared-ui';

const Home: NextPage = () => {
  const clicked = () =>{
      console.log('Clicked');
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Button label="Click me" onClick={clicked} />
      </main>
    </>
  );
};

export default Home;
